name: ripj
favicon: null
layout_spectrum: 0.26197
typography_spectrum: 0.06504
title: "Rkudo's Inspirational Photo Journal"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000002'
    - '#8f9faf'
    - '#554e48'
    - '#72121d'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0
purpose: []
